language: cpp

jobs:
  include:
  - stage: build
    os: linux
    script:
      - "df -h"
      - "pwd"
      - "free -h"
      - "lscpu"

  - stage: build
    os: osx
    script:
      - "df -h"
      - "pwd"
      - "system_profiler SPHardwareDataType"

  - stage: build
    os: windows
    script:
      - df -h
      - pwd
      - powershell -Command  systeminfo
      - echo $NUMBER_OF_PROCESSORS
