version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - run:
          name: Disk
          command: df -h
      - run:
          name: RAM
          command: free -h
      - run:
          name: CPU
          command: lscpu