name: Check vm

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]
  
  

jobs:
  ubuntu1:
    if: ${{ github.ref == 'master' && true }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: env
      run: env
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram
      run: free -h
    - name: Cpu
      run: lscpu

  macos:
    if: ${{ github.ref == 'master' || true }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: print
      run: echo "${{ github.ref}}"
    - name: print
      run: echo "${{ github.head_ref }}"
    - name: print
      run: echo "${{ github }}"
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram cpu
      run: system_profiler SPHardwareDataType

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: env
      run: env
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram
      run: powershell -Command  systeminfo
    - name: CPU1
      run: powershell -Command (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
    - name: Cpu2
      run: echo %NUMBER_OF_PROCESSORS%
