name: Check vm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Disk spase
      run: df -h
    - name: Ram
      run: free -h
    - name: Cpu
      run: lscpu

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Disk spase
      run: df -h
    - name: Ram cpu
      run: system_profiler SPHardwareDataType

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Disk spase
      run: df -h
    - name: Disk spase
      run: pwd
    - name: Ram
      run: powershell -Command  systeminfo
    - name: Cpu
      run: echo $NUMBER_OF_PROCESSORS