name: Check vm

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]
  
env:
  INDOCKER_IMAGE: soramitsu/kagome-dev:8
  

jobs:
  ubuntu1:
    #if: ${{ github.ref == 'refs/heads/master' || startsWith( github.ref, 'refs/tags/' ) }} 
    #container: "{{ env.INDOCKER_IMAGE }}"
    runs-on: ubuntu-latest
    steps:
    - name: pwd
      run: pwd; ls -l
    - name: cpu
      run: nproc || echo '-' ; sysctl -n hw.ncpu || echo '-' ; getconf _NPROCESSORS_ONLN || echo '-' 
    - uses: actions/checkout@v2
    - name: env
      run: env
    - name: git rev-parse --abbrev-ref HEAD
      run: git rev-parse --abbrev-ref HEAD
    - name: git branch
      run: git branch
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram
      run: free -h
    - name: Cpu
      run: lscpu

  macos:
    if: ${{ github.ref == 'master' || true }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: cpu
      run: nproc || echo '-' ; sysctl -n hw.ncpu || echo '-' ; getconf _NPROCESSORS_ONLN || echo '-'
    - name: github.ref
      run: echo "${{ github.ref}}"
    - name: github.head_ref
      run: echo "${{ github.head_ref }}"
    - name: github.base_ref
      run: echo "${{ github.base_ref }}"
    - name: github.event_name
      run: echo "${{ github.event_name }}"
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram cpu
      run: system_profiler SPHardwareDataType

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: cpu
      run: nproc || echo '-'  ; getconf _NPROCESSORS_ONLN || echo '-'
    - name: env
      run: env
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram
      run: powershell -Command  systeminfo
    - name: CPU1
      run: powershell -Command (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
    - name: Cpu2
      run: echo %NUMBER_OF_PROCESSORS%
