name: Check vm

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]
  
env:
  INDOCKER_IMAGE: soramitsu/kagome-dev:8
  

jobs:
  ubuntu1:
    if: ${{ github.ref == 'refs/heads/master' || startsWith( github.ref, 'refs/tags/' ) }} 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: env
      run: env
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram
      run: free -h
    - name: Cpu
      run: lscpu

  macos:
    if: ${{ github.ref == 'master' || true }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: github.ref
      run: echo "${{ github.ref}}"
    - name: INDOCKER_IMAGE
      run: echo "${{ env.INDOCKER_IMAGE }}"
    - name: github.head_ref
      run: echo "${{ github.head_ref }}"
    - name: github.ref == 'refs/heads/master'
      run: echo "${{ github.ref == 'refs/heads/master' }}"
    - name: startsWith( github.ref, 'refs/tags/' )
      run: echo "${{ startsWith( github.ref, 'refs/tags/' ) }}"
    - name: github.ref == 'refs/heads/master' || startsWith( github.ref, 'refs/tags/' )
      run: echo "${{ github.ref == 'refs/heads/master' || startsWith( github.ref, 'refs/tags/' ) }}"
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram cpu
      run: system_profiler SPHardwareDataType

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: env
      run: env
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram
      run: powershell -Command  systeminfo
    - name: CPU1
      run: powershell -Command (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
    - name: Cpu2
      run: echo %NUMBER_OF_PROCESSORS%
