name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Disk spase
      run: df -h
    - name: Ram
      run: free -h
    - name: Cpu
      run: lscpu 
