name: Check vm

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]
  
env:
  INDOCKER_IMAGE: 
  CACHE_PATHS: |
          ~/Library/Caches
          ~/.cache
          ~/.cargo
          ~/.ccache
          ~/.hunter
          ~/.rustup

jobs:
  ubuntu1:
    #if: ${{ github.ref == 'refs/heads/master' || startsWith( github.ref, 'refs/tags/' ) }} 
    container: soramitsu/kagome-dev:10
    runs-on: ubuntu-latest
    steps:
    - name: echo github
      run: echo "${{ toJSON(github) }}"
    - name: echo env
      run: echo "${{ toJSON(env) }}"
    - name: echo job
      run: echo "${{ toJSON(job) }}"
    - name: echo steps
      run: echo "${{ toJSON(steps) }}"
    - name: echo runner
      run: echo "${{ toJSON(runner) }}"
    - name: echo secrets
      run: echo "${{ toJSON(secrets) }}"
    - name: echo strategy
      run: echo "${{ toJSON(strategy) }}"
    - name: echo matrix
      run: echo "${{ toJSON(matrix) }}"
    - name: echo needs
      run: echo "${{ toJSON(needs) }}"
    - name: pwd
      run: pwd; ls -la ~/; ls -la ./.* || true; du -sch ~/.d* || true
    - name: user
      run: whoami; cat /etc/passwd
    - name: env
      run: env 
    - name: Home
      run: cd ~/ ; pwd
    - uses: actions/cache@v2
      with:
        path: ${{ env.CACHE_PATHS }}
        key: ${{ runner.os }} 3
    - name: pwd2
      run: pwd; ls -la ~/; ls -la ./.* || true ; du -sch ~/.d* || true
    - name: cpu
      run: nproc || echo '-' ; sysctl -n hw.ncpu || echo '-' ; getconf _NPROCESSORS_ONLN || echo '-' 
    - uses: actions/checkout@v2
    - name: env
      run: env
    - name: git rev-parse --abbrev-ref HEAD
      run: git rev-parse --abbrev-ref HEAD
    - name: git branch
      run: git branch
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram
      run: free -h
    - name: Cpu
      run: lscpu
    - name: pwd3
      run: pwd; ls -la ~/; ls -la ./.* || true ; du -sch ~/.d* || true

  macos:
    if: ${{ github.ref == 'master' || true }}
    runs-on: macos-latest
    steps:
    - name: echo github
      run: echo "${{ toJSON(github) }}"
    - name: echo env
      run: echo "${{ toJSON(env) }}"
    - name: echo job
      run: echo "${{ toJSON(job) }}"
    - name: echo steps
      run: echo "${{ toJSON(steps) }}"
    - name: echo runner
      run: echo "${{ toJSON(runner) }}"
    - name: echo secrets
      run: echo "${{ toJSON(secrets) }}"
    - name: echo strategy
      run: echo "${{ toJSON(strategy) }}"
    - name: echo matrix
      run: echo "${{ toJSON(matrix) }}"
    - name: echo needs
      run: echo "${{ toJSON(needs) }}"
    - name: befor
      run: |
        ls -la ~/
        ls -la ~/.cache
        ls -la ~/Library/Caches/
        ls -la ~/Library/Caches/pip
        du -sch ~/Library/Caches/pip
    - name: dep
      run: |
        pip3 install --user pyyaml
        sudo python3 -m pip install --upgrade pip
        sudo python3 -m pip install scikit-build
        sudo python3 -m pip install cmake requests gitpython gcovr
        export PATH="$HOME/.cargo/bin:$PATH"
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2019-10-16 --profile minimal 
        echo "------------"
        ls -la ~/
        ls -la ~/.cache
        ls -la ~/Library/Caches/
        ls -la ~/Library/Caches/pip
        du -sch ~/Library/Caches/pip
    - uses: actions/checkout@v2
    - name: cpu
      run: nproc || echo '-' ; sysctl -n hw.ncpu || echo '-' ; getconf _NPROCESSORS_ONLN || echo '-'
    - name: github.ref
      run: echo "${{ github.ref}}"
    - name: github.head_ref
      run: echo "${{ github.head_ref }}"
    - name: github.base_ref
      run: echo "${{ github.base_ref }}"
    - name: github.event_name
      run: echo "${{ github.event_name }}"
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram cpu
      run: system_profiler SPHardwareDataType

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: cpu
      run: nproc || echo '-'  ; getconf _NPROCESSORS_ONLN || echo '-'
    - name: env
      run: env
    - name: Disk spase
      run: df -h
    - name: PWD
      run: pwd
    - name: Ram
      run: powershell -Command  systeminfo
    - name: CPU1
      run: powershell -Command (Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors
    - name: Cpu2
      run: echo %NUMBER_OF_PROCESSORS%
